### ISSUE TITLE
Strafing in Doom needs another modifier key

### ISSUE THREAD

**Issue by sskras** [ringtailsoftware/zig-wasm-audio-framebuffer#1]
`Alt-Left` brings me back into the previous page. Any ideas on how to use different key for that?

**Comment by ringtailsoftware** [comment]
You can change the mappings here:
https://github.com/ringtailsoftware/zig-wasm-audio-framebuffer/blob/master/src/doom/doom.zig#L282
Here are the JavaScript keycodes, https://keyjs.dev/
